
            - name: Modern CMake Buildsystem
  # You may pin to the exact commit or the version.
  # uses: JohelEGP/modern-cmake-buildsystem@c06f1ac47ab9702a74ece675c6c0d245f44f6183
  uses: JohelEGP/modern-cmake-buildsystem@v1.0.0
  with:
    # The top-level directory containing source files provided by the project.
    path-to-source: # optional, default is ${{ github.workspace }}
    # The top-level directory in which buildsystem files and build output artifacts are to be stored.
    path-to-build: # optional, default is ${{ github.workspace }}/build
    # Options to generate a project buildsystem other than `-S` and `-B`.
    generate-options: # optional
    # Options to build a project other than `--build`.
    build-options: # optional
    # Options to test a project.
    test-options: # optional
    # Set to `true` to install the project. Requires CMake 3.15.
    install: # optional
    # Options to install a project other than `--install`.
    install-options: # optional
          
